# Basic settings
title           : Adrián Chávez
email           : adrian.chavez@hey.com
author          : Adrián Chávez
description     : "Adrián Chávez's personal blog"
baseurl         : ""
url             : "https://www.lacf95.com"

# Build settings
theme  : plainwhite
plugins:
  - jekyll-feed

# Plainwhite Theme settings
plainwhite:
  html_lang      : "en"
  name           : "Adrián Chávez"
  tagline        : "Ruby Developer"
  date_format    : "%b %-d, %Y"
  portfolio_image: "assets/images/profile.jpg"

  social_links:
    twitter : lacf95
    github  : lacf95
    linkedIn: in/lacf95

  navigation:
    - title: Posts
      url  : "/"
    - title: About
      url  : "/about/"
